#include:
#  - template: SAST.gitlab-ci.yaml

variables:
  IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}/loadgenerator:${CI_COMMIT_SHORT_SHA}


stages:
#  - test
  - build
  - deploy


build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "$DOCKER_CONFIG" | base64 -d > /kaniko/.docker/config.json
    - /kaniko/executor
        --context "$CI_PROJECT_DIR/loadgenerator"
        --dockerfile "$CI_PROJECT_DIR/loadgenerator/Dockerfile"
        --destination "$IMAGE_NAME"
  tags:
    - kuber

deploy:
  image:
    name: dtzar/helm-kubectl
    entrypoint: [""]
  stage: deploy
  before_script:
    - mkdir ~/.kube/
    - echo $KUBE_CONFIG | base64 > ~/.kube/config
    - export KUBE_CONFIG=~/.kube/config
#    - yc config set token $YC_TOKEN
  script:
#    - kubectl get po
    - helm upgrade --install loadgenerator ./helm --install --set deployment.image=$IMAGE_NAME
  tags:
    - kuber
