replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/loadgenerator
  pullPolicy: IfNotPresent
  tag: "v0.8.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {
  "sidecar.istio.io/rewriteAppHttpProbers": "true"
}
podLabels: {}

podSecurityContext: {
  "fsGroup": 1000,
  "runAsUser": 1000,
  "runAsGroup": 1000,
  "runAsNonRoot": true
}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

env:
  frontend_srv:
  - name: FRONTEND_ADDR
    valueFrom:
      configMapKeyRef:
        name: cmloadgenerator
        key: frontend_srv
  users:
  - name: USERS
    valueFrom:
      configMapKeyRef:
        name: cmloadgenerator
        key: user_count

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
